### ISSUE TITLE
Runtime error when calling zio-cli with subcommands 

### ISSUE THREAD

**Issue by DamianReeves** [zio/zio-cli#136] opened 2022-09-27 19:55 UTC
When I try and run `zio-cli` with the subcommand structure from here: https://github.com/finos/morphir-scala/blob/052462e8accb6003c86532f69cb6cc1f60318189/morphir/tools/cli/src/org/finos/morphir/cli/CliSetup.scala I end up getting a Runtime error due to calling `tail` on a `Nil` list.

```none
timestamp=2022-09-27T19:56:33.343562Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-6" java.lang.UnsupportedOperationException: tail of empty list
        at scala.collection.immutable.Nil$.tail(List.scala:664)
        at zio.cli.ZIOCli.run.macro(ZIOCli.scala:13)"
```

**Comment by adamgfraser** [comment] 2022-09-28 16:19
Thanks for reporting! Will take a look!

**Comment by adamgfraser** [comment] 2022-09-28 17:04
@DamianReeves I am not able to reproduce. Can you please post the command you are running that causes the error as well as ideally a self-contained example without external dependencies?

**Comment by jdegoes** [comment] 2023-05-09 16:46
Closing, please re-open if you can make a reproducer.

**Closed by jdegoes** 2023-05-09 16:46 UTC
Labels: bug
